### ISSUE TITLE
The documentation Link on README does not work.

### ISSUE THREAD

**Issue by stzn** [pointfreeco/swift-macro-testing#1]
### Description

When clicking the Documentation link on README, we've got 404 error.
The link URL is https://pointfreeco.github.io/swift-macro-testing/main/documentation/macrotesting.

![スクリーンショット 2023-09-18 5 15 25](https://github.com/pointfreeco/swift-macro-testing/assets/35151927/3002128d-bc01-4a1a-8cb4-d1c17189b0d9)

I noticed it since I found this page from the [comment](https://forums.swift.org/t/swift-5-9-release-blog-post-community-contributions/67021/9). If the reason of the error is simply because the link has not been ready yet, please close this issue.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-macro-testing/issues) or [discussion](https://github.com/pointfreeco/swift-macro-testing/discussions).

### Expected behavior

We can move to the proper documentation page.

### Actual behavior

We've got 404 error.

**Comment by stzn** [comment]
And I noticed that this link does not work too. (404 error)

![スクリーンショット 2023-09-18 5 17 36](https://github.com/pointfreeco/swift-macro-testing/assets/35151927/137daa47-6f12-4ded-9840-ef1393e01528)

https://www.pointfree.co/episodes/ep250-testing-debugging-macros-part-1

**Comment by stephencelis** [comment]
Hi @stzn, the library is being soft-released a few hours in advance to the videos, and the documentation link is pending generation from swiftpackageindex.com, but should be available shortly. I'm going to close this out as it should resolve itself in the next day, but if you notice any other issues, or if these issues persist much longer, please let us know!

**Comment by stzn** [comment]
> the library is being soft-released a few hours in advance to the videos, and the documentation link is pending generation from swiftpackageindex.com

I see. Thanks for the answer😄
