### ISSUE TITLE
Fatal error on incorrect usage

### ISSUE THREAD

**Issue by gohanlon** [pointfreeco/swift-macro-testing#6]
### Description

On swift-macro-testing 0.2.0 and `main`, the following error in `assertMacro` usage results in a crash:

```swift
    assertMacro {
      """
      @MemberwiseInit
      public struct Pedometer {
        var stepsToday = 0
      }
      """
    } expansion: {
      """
      @MemberwiseInit
      public struct Pedometer {
        var stepsToday = 0
            ┬─────────────
            ╰─ 🛑 @MemberwiseInit requires explicit type declarations for `var` stored properties.
      }
      """
    }
```

My user error was to use the label `expansion:` instead of `diagnostics:`. The crash happens deep into the `SyntaxVisitor.walk` due to an [unsafe unwrap](https://github.com/apple/swift-syntax/blob/509.0.0/Sources/SwiftSyntax/SyntaxChildren.swift#L249). Every one of my tests exercising a diagnostic had this user error and resulted in the same crash.

I discovered this while updating my tests to 0.2.0, using an overly naive find/replace from "matches" to "expansion", having eschewed the given "re-record" advice.

This strikes me as a Swift Syntax issue: I don't think Swift Syntax's `RawSyntaxChildren` is ever intended to ever fatal error, even on bad input. Thoughts?

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-macro-testing/issues) or [discussion](https://github.com/pointfreeco/swift-macro-testing/discussions).

### swift-macro-testing version information

0.2.0, main (3c9424a)

### Xcode version information

Xcode Version 15.0 (15A240d)

**Comment by stephencelis** [comment]
Thanks so much for the report! Can you give #7 a try and see if the experience is somewhat improved?
